[package]
name = "blockchain-benches"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "parity-bench"
path = "src/parity_bench.rs"


[dependencies]
bs58 = "0.5"
bech32 = "0.9.0"
crossbeam-channel = "0.5"
parity-db = "0.5.4"
rand = "0.9.2"