[workspace]
resolver = "3"
members = [
    "core",
    "storages/fjall",
    "storages/redb",
    "storages/rocksdb",
    "storages/mdbx",
    "storages/parity",
    "storages/fst",
]
default-members = ["core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
